<?php
/**
 * @package ET_Filter
 * @version 1.0.4
 * @copyright Copyright (c) 2014 EcomTheme. (http://www.ecomtheme.com)
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');


if (! $_productCollection->count()) : ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php
else :

    if (! $this->getRequest()->isAjax()) : ?>
<div id="ajax-errors" style="display: none;">
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <li><span><?php echo $this->__('An error occurred, please try again later.'); ?></span></li>
                </ul>
            </li>
        </ul>
    </div>
    <div id="loading_filter" style="display: none; margin-bottom: 10px; text-align: center;">
        <img alt="" src="<?php echo $this->getSkinUrl('images/loader.gif'); ?>">
    </div>

    <div id="category-products-wrap">
    <?php
    endif; ?>

        <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
            
        <?php if($this->getMode() != 'grid') : ?>
            <ol class="products-list" id="products-list">
            <?php
            foreach ($_productCollection as $_product) :
                $is_new = Mage::helper('oxynic')->isNew($_product);
                $is_special = Mage::helper('oxynic')->isSpecial($_product);
                $condition = $product->getAttributeText('special');
                ?>
                <li class="item">
                    <?php // Product Image ?>
                    <div class="product-image">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250,250); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a>
                        <?php
                        if ($is_new && !$is_special) {
                            echo "<span class='new-product'>".$this->__('New With Tags')."</span>";
                        }
                        if ($is_new && $is_special) {
                            echo "<span class='new-product'>".$this->__('New With Tags')."</span>";
                        }
                        if ($condition){
                            echo "<span class='new-product'>".$this->__('Tiny Flaw')."</span>";
                        } ?>
                        <?php if (Mage::helper('core')->isModuleEnabled('ET_Ajax') && Mage::helper('ajax')->isQuickviewEnabled() ): ?>
                            <div class="item-quickview">
                                <a href="<?php echo Mage::helper('ajax')->getQuickviewUrl($_product); ?>">Quick View</a>
                            </div>
                        <?php endif; ?>
                    </div>
                    <?php // Product description ?>
                    <div class="product-shop">
                        <div class="f-fix">
                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <div class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
                                    <?php
                                    $product_name=$_helper->productAttribute($_product, $_product->getName() , 'name');
                                    if (strlen($product_name)>24){
                                    $product_name=substr($product_name,0,24);
                                    $product_name.="...";
                                    }
                                    ?>
                                   <?php echo $product_name; ?>
                                </a>
                            </div>
                            
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short', true); ?>
                            <div class="csw">
                            <?php
                            // Provides extra blocks on which to hang some features for products in the list
                            // Features providing UI elements targeting this block will display directly below the product name
                            if ($this->getChild('name.after')) {
                                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                    $_nameAfterChild->setProduct($_product);
                                    echo $_nameAfterChild->toHtml();
                                }
                            }
                            ?>
                            </div>
                            <?php echo $this->getPriceHtml($_product, true, '_listing_list'); ?>
                            
                            <div class="item-cwc-wrap-list">
                                <?php if($_product->isSaleable()) : ?>
                                    <div class="item-addcart">
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    </div>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <div class="item-wishlist">
                                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                                    </div>
                                <?php endif; ?>
                                
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)) : ?>
                                    <div class="item-compare">
                                        <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                            
                            <div class="desc std">
                                <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            </div>
                                
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
            </ol>
    
            <?php else: ?>
    
            <?php // $_collectionSize = $_productCollection->count() ?>
            <?php // $_columnCount = $this->getColumnCount(); ?>
            <div class="products-grid">
                <div class="row">
                <?php $i=0;
                foreach ($_productCollection as $_product) :
                    $is_new = Mage::helper('oxynic')->isNew($_product);
                    $is_special = Mage::helper('oxynic')->isSpecial($_product);
                    $condition = $_product->getAttributeText('special');
                    
                    ?>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 item">
                        <?php if ($_product->isSaleable()) : ?>
                        <div class="product-image">

                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(185,268)->setQuality(100); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>
                            <?php
                            if ($condition  == 'New With Tag') {
                                echo "<span class='new-product'>".$this->__('New With Tag')."</span>";
                            }
                            /*if ($is_new && $is_special) {
                                echo "<span class='new-product'>".$this->__('New with tag')."</span>";
                            }*/
                            if ($condition  == 'Gently Used') {
                                echo "<span class='gently-product'>".$this->__('Tiny Flaw')."</span>";
                            } ?>
                            <?php if (Mage::helper('core')->isModuleEnabled('ET_Ajax') && Mage::helper('ajax')->isQuickviewEnabled()) : ?>
                                <div class="item-quickview">
                                    <a href="<?php echo Mage::helper('ajax')->getQuickviewUrl($_product); ?>"><?php echo $this->__('Quick View');?></a>
                                </div>
                            <?php endif; ?>
                        </div>

                        <?php else: ?>
                        <div class="product-image" >

                            <a style="opacity:0.3;" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(185,268)->setQuality(100); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a>
                            <?php
                            if ($condition  == 'New With Tag') {
                                echo "<span class='new-product'>".$this->__('New With Tag')."</span>";
                            }
                            /*if ($is_new && $is_special) {
                                echo "<span class='new-product'>".$this->__('New with tag')."</span>";
                            }*/
                            if ($condition  == 'Gently Used') {
                                echo "<span class='gently-product'>".$this->__('Tiny Flaw')."</span>";
                            } ?>
                            <?php if (Mage::helper('core')->isModuleEnabled('ET_Ajax') && Mage::helper('ajax')->isQuickviewEnabled()) : ?>
                                <div class="item-quickview">
                                    <a href="<?php echo Mage::helper('ajax')->getQuickviewUrl($_product); ?>"><?php echo $this->__('SOLD OUT');?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                        <?php endif; ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true); ?>">
                        <div class="product-info">
                            <span class="brands" style="display:block;"><?php echo $_product->getAttributeText('brands'); ?></span> <!--New Catalog Page-->
                            <div class="product-name">
                                
                                    
                                      <?php
                                    $product_name=$_helper->productAttribute($_product, $_product->getName() , 'name');
                                    if (strlen($product_name)>19){
                                    $product_name=substr($product_name,0,19);
                                    $product_name.=" ...";
                                    }
                                    ?>
                                   <?php echo $product_name; ?>
                                </a>
                            </div>
                            <div>
                            <?php
                            // print_r($_product->getData());
                            // Provides extra blocks on which to hang some features for products in the list
                            // Features providing UI elements targeting this block will display directly below the product name
                            if ($this->getChild('name.after')) {
                                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                    $_nameAfterChild->setProduct($_product);
                                    echo $_nameAfterChild->toHtml();
                                }
                            }
                            ?>
                            
                            <span class="product-size" style="display:block;"><?php echo $this->__('Size: ') ?><?php echo $_product->getAttributeText('size'); ?></span>
                            </div>
                            
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short', true); ?>
                            <?php echo $this->getPriceHtml($_product, true, '_listing_grid'); ?>

                            <div class="item-cwc-wrap">
                                <div class="item-cwc-inner">
                                    <?php if ($_product->isSaleable()) : ?>
                                        <div class="item-addcart">
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span"><?php echo $this->__('Add to Cart') ?></span></span></button>
                                        </div>
                                    <?php else: ?>
                                        <div class="item-addcart">
                                            <button style="background-color:#ff0252; color:#ffffff;" type="button" title="<?php echo $this->__('SOLD') ?>" class="button btn-cart"><span><span"><?php echo $this->__('Sold') ?></span></span></button>
                                        </div>

                                       <!-- <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>-->
                                    <?php endif; ?>
    
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <?php if ($_product->isSaleable()) : ?>
                                            <div class="item-wishlist">
                                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <div class="item-compare">
                                            <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <?php endforeach ?>
                </div>
            </div>
            <?php endif; ?>
    
            <div class="toolbar-bottom">
                <?php //echo $this->getToolbarHtml() ?>
            </div>
        </div>
    <?php
    if (! $this->getRequest()->isAjax()): ?>
    </div>
    <?php
    // Provides a block where additional page components may be attached, primarily good for in-page JavaScript
    if ($this->getChild('after')) {
        $_afterChildren = $this->getChild('after')->getSortedChildren();
        foreach ($_afterChildren as $_afterChildName) {
            $_afterChild = $this->getChild('after')->getChild($_afterChildName);
            //set product collection on after blocks
            $_afterChild->setProductCollection($_productCollection);
            echo $_afterChild->toHtml();
        }
    }
    
    endif;
endif;

if (Mage::helper('filter')->isAjaxEnabled() && !$this->getRequest()->isAjax()) : ?>
<div id="scrolling_loder">
<span class="loader_img"><img src="<?php echo $this->getSkinUrl("images/loading.gif");?>" /></span>
<span>Loading More Products</span>
</div>
<script type="text/javascript">
    //<![CDATA[
    function pushState(data, link, replace) {
        if (!window.History.enabled)  return false;
        window.History[replace ? 'replaceState' : 'pushState'](data, document.title, link);
    }
    
    function handleEvent(el, event) {
        var url, fullUrl;
        if (typeof el === 'string') {
            url = el;
        } else if (el.tagName.toLowerCase() === 'a') {
            url = $(el).readAttribute('href');
        } else if (el.tagName.toLowerCase() === 'select') {
            url = $(el).getValue();
        }

        if (url.indexOf('?') != -1) {
            fullUrl = url + '&isLayerAjax=1';
        } else {
            fullUrl = url + '?isLayerAjax=1';
        }
        
        showLoading();
        $('ajax-errors').hide();

       history.pushState(data, event.target.textContent, event.target.href);

       return event.preventDefault();
       
       window.addEventListener('popstate', function(event) {
       console.log('popstate fired!');

       updateContent(event.state);
   });
        
        pushState(null, url, false);
        
        new Ajax.Request(fullUrl, {
            method: 'get',
            onFailure: function(){
                $('ajax-errors').show();
            },
            onSuccess: function(transport) {
                if (transport.responseJSON) {
                    var err = 0;
                    if (transport.responseJSON.listing) {
                        
                        $('category-products-wrap').update(transport.responseJSON.listing);
                        if (typeof handleUrls == 'function') handleUrls();
                    } else {
                        err++;
                    }
                    if (transport.responseJSON.layer) {
                        $('layered-navigation').update(transport.responseJSON.layer);
                    } else {
                        err++;
                    }
                    if (!err) {
                        pushState({
                            listing: transport.responseJSON.listing,
                            layer: transport.responseJSON.layer
                        }, url, true);
                        addEvents();
                    } else {
                        $('ajax-errors').show();
                    }
                } else {
                    $('ajax-errors').show();
                }
                hideLoading();
            }
        });
        
        event && event.preventDefault();
    }
    
    function addEvents() {
        var els;
        els = $$('div.pager a').concat(
            $$('div.sorter a'),
            $$('div.pager select'),
            $$('div.sorter select'),
            $$('div.block-layered-nav a')
        );
        els.each(function(el) {
            if (el.tagName.toLowerCase() === 'a') {
                $(el).observe('click', function(event) {
                    handleEvent(this, event);
                });
            } else if (el.tagName.toLowerCase() === 'select') {
                $(el).setAttribute('onchange', '');
                $(el).observe('change', function(event) {
                    handleEvent(this, event);
                });
            }
        });
    }
    
    document.observe("dom:loaded", function() {
        addEvents();
        
        +function(History) {
            if (!History.enabled) return false;

            pushState({
                listing: $('category-products-wrap').innerHTML,
                layer: $('layered-navigation').innerHTML
            }, document.location.href, true);

            // Bind to StateChange Event
            History.Adapter.bind(window, 'popstate', function(event) {
                if (event.type == 'popstate') {
                    var newState = History.getState();
                    $('category-products-wrap').update(newState.data.listing);
                    $('layered-navigation').update(newState.data.layer);
                    addEvents();
                }
            });
        }(window.History);
    });
    //]]>
</script>
<?php
endif;