<div class="why-prelove quality-accordion col-lg-12 col-md-12 col-sm-12 col-xs-12">
<div class="preluv col-lg-4 col-md-4 col-sm-4 col-xs-4"><img alt="" src="http://www.rekinza.com/images/homepage/quality3.png" /></div>
<div class="preluv col-lg-4 col-md-4 col-sm-4 col-xs-4"><img alt="" src="http://www.rekinza.com/images/homepage/saving3.png" /></div>
<div class="preluv col-lg-4 col-md-4 col-sm-4 col-xs-4"><img alt="" src="http://www.rekinza.com/images/homepage/shop-cause3.png" /></div>
</div>
