<div class="shipping">
    <h3>SHIPPING & RETURNS</h3>
    <strong>Shipping</strong>

<p>FREE shipping on orders of Rs.1000 or more. Shipping charge of Rs.100 will be charged on orders under Rs.1000. Once shipped, your order will be delivered in 3-8 business days.</p>

<strong>Returns</strong>

<p>If an item doesn’t work out for you for any reason, feel free to return it within 3 days of receiving it. You don’t need to include an invoice or the original packaging. Please just remember that the item must be in its original condition (unworn, unwashed, and with all tags/accessories attached and handbags sent with the manufacturer dust bag must have the dust bag returned as well) and requested for return within 3-days of receipt to be eligible for a full refund.
<br/>
<br/>
<a style="color:#f05865;" href="http://www.rekinza.com/thredshare_returns/returns/getreturns/">Return Form</a>
</div>