<div class="f-tab">
    <div class="first-sentence">WHY <span class="highlight">REKINZA</span></div>
    <ul>
        <li>
            <img src="http://www.thredshare.com/skin/frontend/et_oxynic/default/images/home-sec1.jpg"/>
            <div class="sub-dcrip">Your favourite  brands at unbelievable bragains we authenticate each product & triple check for quality. Free shipping and hassle-free returns.</div>
            <div class="Lmore">Learn More</div>
        </li>
        <li>
            <img src="http://www.thredshare.com/skin/frontend/et_oxynic/default/images/home-sec2.jpg"/>
            <div class="sub-dcrip">Your favourite  brands at unbelievable bragains we authenticate each product & triple check for quality. Free shipping and hassle-free returns.</div>
            <div class="Lmore">Learn More</div>
        </li>
        <li>
            <img src="http://www.thredshare.com/skin/frontend/et_oxynic/default/images/home-sec3.jpg"/>
            <div class="sub-dcrip">Your favourite  brands at unbelievable bragains we authenticate each product & triple check for quality. Free shipping and hassle-free returns.</div>
            <div class="Lmore">Learn More</div>
        </li>
    </ul>
</div>
<div class="s-tab">
    <div class="first-sentence">THE REKINZA<span class="highlight">MOVIE</span></div>
    <div class="movie">
        
    </div>
    
</div>
<div class="t-tab">
    <div class="first-sentence">FEATURED<span class="highlight">PRODUCTS</span></div>
    <div class="sub-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin blandit neque </div> 
    <ul class="tab-4th">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
    
</div>
<div class="th4-tab">
    <div class="first-sentence"><span class="highlight">BRANDS</span> WE LOVE</div>
    <div class="sub-text">Women's Clothing, Bag and Shoes</div> 
    
    
    <div class="Allsegment">
        <div class="segment">
            <h1>EVERYDAY</h1>
            <ul><li></li><li></li><li></li><li></li></ul>
        </div>
        <div class="segment"><h1>DESIGNER PICKS</h1>
            <ul><li></li><li></li><li></li><li></li></ul>
        </div>
        <div class="segment">
            <h1>INDIAN DESIGNERS</h1>
            <ul><li></li><li></li><li></li><li></li></ul>
        </div>
        <div class="segment">
            <h1>LUXURY CLASSICS</h1>
            <ul><li class="noborder"></li><li class="noborder"></li><li class="noborder"></li><li class="noborder"></li></ul>
        </div>
    </div>
        

</div>