<?php
/**
 * @package ET_Ajax
 * @version 1.0.4
 * @copyright Copyright (c) 2014 EcomTheme. (http://www.ecomtheme.com)
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */


/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */
?>

<div class="block-cart header-cart pull-right" id="ajaxcart">

	<?php include dirname(__FILE__).'/cart/inside.phtml'; ?>
</div>