<?php
/**
 * @package ET_Filter
 * @version 1.0.4
 * @copyright Copyright (c) 2014 EcomTheme. (http://www.ecomtheme.com)
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="<?php if ($_item->isSelected()) echo $this->__('active'); ?>">
            <?php if ($_item->getCount() > 0): ?>
                
                <a href="<?php echo ($_item->isSelected()) ? $_item->getRemoveUrl() : $_item->getUrl() ?>"
                    ><?php echo $_item->getLabel() ?>
				</a>
                <?php else: ?>
                    <?php echo $_item->getLabel() ?>
                <?php endif; ?>
				
				<?php if ($this->shouldDisplayProductCount()): ?>
				(<?php echo $_item->getCount() ?>)
				<?php endif; ?>
		
        </li>
    <?php endforeach ?>
</ol>