<?php $quote = Mage::getSingleton('checkout/session')->getQuote();
	  $rewardpoints = $quote->getMwRewardpoint();
	  $reward_point_sell_product = $quote->getMwRewardpointSellProduct();
	  $store_id = Mage::app()->getStore()->getId();

	  $total_reward_point = $rewardpoints + $reward_point_sell_product;
	  ?>


<?php if($total_reward_point):?>
	<tr>
	    <td colspan="3" class="a-right" colspan="1"><?php echo Mage::helper("rewardpoints")->__("KinzaCash Redeemed");?></td>
	    <td class="a-right"><span class="price"><?php echo $total_reward_point?></span></td>
	</tr> 
<?php endif;?>
