<?php echo $this->getChildHtml('items_before'); ?>

<div id="checkout-review-table-wrapper">
    <table class="table data-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col width="1"/>
        <col width="1"/>
        <col width="1"/>
        <col width="1"/>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <col width="1"/>
            <col width="1"/>
        <?php endif; ?>
        <col width="1"/>
        <thead>
        <!--tr>
            <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
            <th rowspan="<?php echo $rowspan ?>" wrap="wrap" class="a-center"><?php echo $this->__('Qty') ?></th>
            <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
           <th colspan="<?php echo $colspan ?>" class="a-center remove-item-diplay" style="display: none;"></th>
        </tr-->
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <tr>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                <!--<th></th> -->
            </tr>
        <?php endif; ?>
        </thead>
        <tbody>
        <?php foreach ($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach ?>
        
        </tbody>
		<table id = "order_payment_details" class="table data-table">
			<?php echo $this->getChildHtml('totals'); ?>
		</table>
		<button class="continue_button" role='review-save' type="submit"
                    title="<?php echo Mage::helper('checkout')->__('Place Order') ?>" name="submitbtn"
                    id="lbonepage-place-order-btn" class="button btn-checkout finalorder">
                <span><span><?php echo Mage::helper('checkout')->__('Place Order') ?></span></span>
        </button>
        <div class="badge-icon">
            <img src="http://www.rekinza.com/images/badge-buyer-protect.png" style="width:100%; margin:auto;"/>
        </div>

    </table>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">//jQuery('#checkout-review-table').decorate('table');</script>
<div id="checkout-review-submit">

</div>
<div id="checkout-paypaliframe-load" class="authentication white-popup mfp-hide"></div>
<div class="clearfix"></div>
<script type="text/javascript">
    //<![CDATA[
    review = new Review();
    //]]>
	jQuery("#lbonepage-place-order-btn").unbind().click(function() {
    console.log("orderplaced");
    ga('send', 'event', 'order place', 'click', 'order place', {'nonInteraction': 1}); 
});
</script>


