<table>
	<tr><td>
			<?php $store_id = Mage::app()->getStore()->getId();?>
			<p class="amount"><?php echo $this->__('Your KinzaCash balance is <strong class="highlight">%s</strong>',Mage::helper('rewardpoints')->formatPoints($this->getRewardPoints(),$store_id)) ?></p>
	
	</td>
	</tr>
	<tr><td>
		<p>You can <span class="highlight"><a style="color:rgb(255, 32, 82);" href="<?php echo $this->getUrl("rewardpoints/rewardpoints/cashout");?>">Cash Out</a></span> or use the credit to <span class="highlight"><a style="color:rgb(255, 32, 82);"  href="<?php echo Mage::getBaseUrl()."clothing";?>">Shop</a></span></p>
	
	</td>
	</tr>
	<tr>
	
	<td>
		<form name="mw_rewardpoints_coupon" id="mw_rewardpoints_coupon" action="<?php echo $this->getUrl('rewardpoints/rewardpoints/coupon');?>" method="post">
			<div style="width:230px; float:left; font-weight: bold;"><label><?php echo $this->__("Coupon code:")?> </label><input type="text" name="coupon_code" class="input-text required-entry mw-rewardpoint-validate-coupon-code" /></div>
			<div style="float:left; text-align: right;"><button type="submit" title="<?php echo $this->__("Submit")?>" class="button"><span><span><?php echo $this->__("Submit")?></span></span></button></div>
		</form>
	</td>
	
	</tr>
</table>



<script type="text/javascript">
//<![CDATA[
    var exchangeForm = new VarienForm('mw_rewardpoints_coupon', true);
    //]]>
</script>