<div id="transaction_history_box">
<?php echo $this->getToolbarHtml()?>
<?php $transactions = $this->getTransaction();
if ($transactions!=null && $transactions->count()>0):
?>

<table id="my-transaction-table" class="kinzacash-table">
<!--     <col width="10">
    <col width="10">
    <col width="20">
    <col width="20">
    <col width="40">
    <col width="20"> -->
        <thead>
            <tr>
            	<th class="hidden-xs"><?php echo $this->__("S.No")?></th>
            	<th><?php echo $this->__("Date")?></th>
            	<th colspan="2"><?php echo $this->__("Details")?></th>
                <th><?php echo $this->__("Transaction Amount")?></th>
                <th><?php echo $this->__("Account Balance")?></th>
				<th class="hidden-xs"><?php echo $this->__("Status")?></th>
            </tr>
        </thead>
        <tbody>
        <?php 
        $i = 0;
        foreach($transactions as $transaction):?>
		<?php 
		$i++;
		/*mage::log($transaction->getData());
		$type=$transaction->getType();
		   if ($type=="deposit"){
		   $amount="+".$transaction->getPoints();
		   $message=$transaction->getMessage();
		   $status="Deposited";
		   }else{
		   $amount="-".$transaction->getPoints();
		   $message=explode(";",$transaction->getMessage());
		   $message=implode("<br>",$message);
		   $message=preg_replace("/\\n/","<br>",$message); */
		   $status_int=$transaction->getStatus();
		   if ($status_int==0){
		   $status="pending";
		   }else{
		   $status="completed";
		   }
		   //} 

		   $d_o_t = $transaction->getTransactionTime();
		   $only_date = explode(" ", $d_o_t); ?>          
		  <tr>	
		  	<td class="hidden-xs" style="text-align: center;"><?php echo $i//echo $transaction->getData('id')?></td>
			<td style="text-align: center;"><?php echo $only_date[0] ?> </td>
			<td colspan="2"><?php echo $transaction->getTransactionDetail();?></td>
			<td style="text-align: center;"><?php echo $transaction->getAmount()?> </td>
	        <td style="text-align: center;"><span class="price"><?php echo $transaction->getBalance();?></span></td>
			<td class="hidden-xs" style="text-align: center;"><?php echo $status;?></td>
          </tr>
        <?php endforeach;?>
      	</tbody>
</table>
<?php else:?>
<?php echo "You do not have any Kinza Cash transactions.";?>
<?php endif;?>

<?php //echo $this->getToolbarHtml()?>

</div>
<script type="text/javascript">decorateTable('my-transaction-table')</script>